### ISSUE TITLE
Geen scherm

### ISSUE THREAD

**Issue by remcoswienink** [marktplaatstabel/Marktplaatstabel#1]
Chrome en W7: na installatie en reboot opent bij het starten van het programma ssl.marktplaatstabel.services/marktplaatstabel in Chrome. Helaas is dit een witte pagina, zonder opties.
Op de pagina van Marktplaats Plaats een advertentie zie ik ook geen extra opties.

Is het gebruik van dit systeem toegestaan door MP?

**Comment by marktplaatstabel** [comment]
Windows kan ik op het moment niet testen. Linux werkt goed. Misschien firewall instellingen?

**Comment by remcoswienink** [comment]
Firewall staat op Vraag permissie en ik krijg geen verzoeken. Denk niet dat dat het probleem is.

**Comment by ivovk** [comment]
![screenshot from 2015-02-08 00 36 19](https://cloud.githubusercontent.com/assets/4053447/6094439/b4b7412e-af2a-11e4-82df-3133a1ee8494.png)
Screenshot chrome en Windows 7 in virtual box. Gelijk na installatie van Windows 7, Marktplaatstabel geinstalleerd. Hij startte niet automatisch aan het einde van het installatieprogramma, en moest nog een keer op Marktplaats starten klikken. Geen WOD.

**Comment by remcoswienink** [comment]
Na het starten van Marktplaats starten geeft bij mij een witte pagina ssl.marktplaatstabel.services/marktplaatstabel

**Comment by remcoswienink** [comment]
hosts bestand:
127.0.0.1       localhost
127.0.0.1       marktplaatstabel.services www.marktplaatstabel.services
127.0.0.1       ssl.marktplaatstabel.services

**Comment by ivovk** [comment]
Helemaal goed. Evt. kan ik inloggen met teamviewer om te kijken waar het misgaat.
Tijdens de installatie kreeg ik wel een scherm met een verzoek van Joyent Node.js om toegang tot het publieke netwerk. Marktplaatstabel is geschreven in Node.js en Javascript.

**Comment by remcoswienink** [comment]
Dat vind ik prima, hoe kunnen we dat regelen?

**Comment by marktplaatstabel** [comment]
Als je teamviewer installeert dan zie je een scherm met ID en wachtwoord, daarmee kan ik inloggen (http://www.teamviewer.com/nl/products/remotecontrol.aspx).

**Comment by remcoswienink** [comment]
Prima, komt het nu uit?

**Comment by marktplaatstabel** [comment]
Sorry, ik lees je bericht nu pas. Zet het even in een mail naar ivo.vankampATgmail.com met tijd en id. Dan log ik dan in.
